runtime: custom
service: apitest
env: flex
runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.9"

entrypoint: gunicorn -b :$PORT manage:app
env_variables:
    DATABASE_URL: "postgresql://eporra:eporra@35.232.130.12:5432/postgres"
    FLASK_APP: "apostador/__init__.py"
    FLASK_DEBUG: "1"

automatic_scaling:
    max_num_instances: 1
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300 #-> increase to 3600

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2